s=input()
i,j=map(int,input().split())
i=i-1
i1=j%len(s)
i2=i%len(s)
l1=s[:i1]
l2=s[:i2]
cc=len(s)-len(s.replace("B",""))
c1=(j//len(s))*cc
c2=(i//len(s))*cc
n1=len(l1)-len(l1.replace("B",""))
n2=len(l2)-len(l2.replace("B",""))
fin=c1+n1-n2-c2
print(fin)
